exclude: '^api/migrations|^docs|^pipeline/src/sample_data'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - args:
          - --fix=lf
        id: mixed-line-ending

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        name: 'API Black Format'
        files: '^api/'
      - id: black
        name: 'Pipeline Black Format'
        files: '^pipeline/'

  - repo: https://github.com/asottile/reorder_python_imports
    name: 'Reorder Imports'
    rev: v3.1.0
    hooks:
      - id: reorder-python-imports

  - repo: https://github.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
        language_version: python3
        args: [--config, .flake8]
