version: "3"
services:
  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: checkstatusgovbr/api
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/checkstatusgovbr
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - db

  db:
    build: ./api/postgres
    image: checkstatusgovbr/postgres
    volumes:
      - $HOME/.postgres/checkstatusgovbr/data/postgresql:/var/lib/postgresql/data
      - ./data:/tmp/data
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DBS=checkstatusgovbr, checkstatusgovbrtest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  alembic:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: checkstatusgovbr/db-migration
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/checkstatusgovbrtest
    volumes:
      - ./api/migrations:/usr/src/app/migrations
    command: poetry run alembic upgrade head
    depends_on:
      - db

  pipeline:
    build:
      context: ./pipeline
      dockerfile: Dockerfile
      target: pipeline
    image: checkstatusgovbr/pipeline
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/checkstatusgovbr
    volumes:
      - ./pipeline:/usr/src/app/pipeline
    depends_on:
      - alembic

  pipeline-test:
    build:
      context: ./pipeline
      dockerfile: Dockerfile
      target: pipeline-local
    image: checkstatusgovbr/pipeline
    environment:
      - TEST_DATABASE_URL=postgresql://postgres:postgres@db:5432/checkstatusgovbrtest
    volumes:
      - ./pipeline:/usr/src/app/pipeline
    command: poetry run pytest ./pipeline/tests
    depends_on:
      - alembic

  plantuml:
    build:
      context: ./docs
    image: checkstatusgovbr/plantuml-cli
    container_name: plantuml_cli
    volumes:
      - ./docs/assets:/usr/docs/assets
