version: "3"
services:
  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: checkstatusgovbr/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/checkstatusgovbr
    volumes:
      - .:/home/app
    depends_on:
      - db

  db:
    build: ./api/postgres
    image: checkstatusgovbr/postgres
    volumes:
      - $HOME/.postgres/checkstatusgovbr/data/postgresql:/var/lib/postgresql/data
      - ./data:/tmp/data
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DBS=checkstatusgovbr, checkstatusgovbr_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  plantuml:
    build:
      context: ./docs
    image: checkstatusgovbr/plantuml-cli
    container_name: plantuml_cli
    volumes:
      - ./docs/assets:/usr/docs/assets