version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.api
    image: checkstatusgovbr/api
    ports:
      - "8000:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/checkstatusgovbr
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - db

  db:
    build: ./api/postgres
    image: checkstatusgovbr/postgres
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DBS=checkstatusgovbr, checkstatusgovbrtest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - db_tmp:/tmp/data

  alembic:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: checkstatusgovbr/db-migration
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/checkstatusgovbr
    volumes:
      - ./api/migrations:/usr/src/app/migrations
    command: poetry run alembic upgrade head
    depends_on:
      - db

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - CHECKSTATUS_API_URL=http://api:8000
    volumes:
      - ./frontend:/app
    depends_on:
      - app

  alembic-test:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: checkstatusgovbr/db-migration
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/checkstatusgovbrtest
    volumes:
      - ./api/migrations:/usr/src/app/migrations
    command: poetry run alembic upgrade head
    depends_on:
      - db

  pipeline:
    build:
      context: ./pipeline
      dockerfile: Dockerfile
      target: pipeline
    image: checkstatusgovbr/pipeline
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/checkstatusgovbr
    volumes:
      - ./pipeline:/usr/src/app/pipeline
    depends_on:
      - alembic

  pipeline-test:
    build:
      context: ./pipeline
      dockerfile: Dockerfile
      target: pipeline-local
    image: checkstatusgovbr/pipeline
    environment:
      - TEST_DATABASE_URL=postgresql://postgres:postgres@db:5432/checkstatusgovbrtest
    volumes:
      - ./pipeline:/usr/src/app/pipeline
    command: poetry run pytest ./pipeline/tests
    depends_on:
      - alembic

  scheduler:
    build:
      context: ./
      dockerfile: Dockerfile.scheduler
      target: final
    image: checkstatusgovbr/scheduler
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/checkstatusgovbr
    volumes:
      - ./scheduler:/app/scheduler
    depends_on:
      - db

  plantuml:
    build:
      context: ./docs
    image: checkstatusgovbr/plantuml-cli
    container_name: plantuml_cli
    volumes:
      - ./docs/assets:/usr/docs/assets

volumes:
  db_data:
  db_tmp:
