"""Add available column

Revision ID: 86f8fff08103
Revises: 99a7a873ed25
Create Date: 2023-10-09 18:38:31.773584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "86f8fff08103"
down_revision = "99a7a873ed25"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "domains",
        sa.Column("available", sa.Boolean(), nullable=False, server_default="false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("domains", "available")
    # ### end Alembic commands ###
