"""

Revision ID: 99a7a873ed25
Revises: 536d53c5f4d1
Create Date: 2023-01-27 19:45:22.005760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "99a7a873ed25"
down_revision = "536d53c5f4d1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "domains", sa.Column("document_normalized", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "domains",
        sa.Column("organization_normalized", sa.String(length=256), nullable=False),
    )
    op.add_column(
        "domains", sa.Column("agent_normalized", sa.String(length=256), nullable=True)
    )
    op.add_column(
        "domains",
        sa.Column("nameservers", postgresql.ARRAY(sa.String()), nullable=True),
    )
    op.add_column(
        "domains", sa.Column("department", sa.String(length=256), nullable=True)
    )
    op.add_column(
        "domains",
        sa.Column("department_normalized", sa.String(length=256), nullable=True),
    )
    op.add_column(
        "domains", sa.Column("department_email", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "domains", sa.Column("status", postgresql.ARRAY(sa.String()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("domains", "status")
    op.drop_column("domains", "department_email")
    op.drop_column("domains", "department_normalized")
    op.drop_column("domains", "department")
    op.drop_column("domains", "nameservers")
    op.drop_column("domains", "agent_normalized")
    op.drop_column("domains", "organization_normalized")
    op.drop_column("domains", "document_normalized")
    # ### end Alembic commands ###
