name: API Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "api/**"

env:
  DEBUG: false

jobs:
  migrate:
    name: Run Database Migrations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl proxy 5432:5432 -a checkstatusgovbr-db &> /dev/null &
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Execute alembic migrations
        run: |
          pip install -U pip
          pip install poetry
          poetry install
          poetry run alembic upgrade head
        working-directory: api
        env:
          POETRY_VIRTUALENVS_CREATE: false
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

  deploy:
    name: Prepare Deploy
    needs: migrate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy -a checkstatusgovbr
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
