name: Pipelines CI/CD

on: pull_request

jobs:
  linter:
    name: Mypy, Black and Flake8 Linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Deps
        run: |
          pip install -U pip
          pip install poetry
          poetry install
        working-directory: pipeline
        env:
          POETRY_VIRTUALENVS_CREATE: false
      - name: Run Black checks
        run: poetry run black --check .
        working-directory: pipeline
      - name: Run Flake8 checks
        run: poetry run flake8 --count .
        working-directory: pipeline
      - name: Run MyPy checks
        run: poetry run mypy .
        working-directory: pipeline

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Deps
        run: |
          pip install -U pip
          pip install poetry
          poetry install
        working-directory: pipeline
        env:
          POETRY_VIRTUALENVS_CREATE: false
      - name: Run pytest check
        run: poetry run pytest -vv
        working-directory: pipeline
