name: Pipeline Main

on:
  pull_request:
  push:
    branches:
      - main

env:
  DEBUG: false

jobs:
  migrate:
    name: Run Database Migrations
    runs-on: ubuntu-latest
    steps:
          - uses: superfly/flyctl-actions/setup-flyctl@master
          - run: "fly proxy 5432:5432 -a checkstatusgovbr"
            env:
              FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          - uses: actions/checkout@v2
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: "3.10"
          - name: Execute alembic migrations
            run: |
              pip install -U pip
              pip install poetry
              poetry install
              poetry run alembic upgrade head
            working-directory: api
            env:
              POETRY_VIRTUALENVS_CREATE: false
              DATABASE_URL: ${{ secrets.DATABASE_URL }}
